//+------------------------------------------------------------------+
//|                                          TelemetryTypes.mqh        |
//|                                      Copyright 2026, SuperCents_X|
//|                                             Sprint 14 (v2.9)       |
//+------------------------------------------------------------------+
//  @frozen v2.9  TelemetryRow  (schemaVersion = 1)
//  @frozen v2.9.2 TelemetryRow  (schemaVersion = 2)
//  @frozen v3.1   TelemetryRow  (schemaVersion = 3)
//  @schema v3.1   TelemetryRow  (schemaVersion = 4)  [Sprint 20 TC01]
//  @schema v5     TelemetryRow  (schemaVersion = 5)  [Sprint 22 RL-HYP-01]
//  @schema v6     TelemetryRow  (schemaVersion = 6)  [Sprint 25B B25-01]
//
//  CONTRACT RULES (append-only, never break):
//  - Column order and semantics are frozen once data collection starts.
//  - Never rename or reorder existing fields/columns.
//  - Reserved fields (actualOutcome, actualOutcomeSource) remain empty
//    until used; they must never be repurposed.
//  - New fields require a schemaVersion bump and an append-only CSV
//    migration (new columns at the END of the header).
//
//  v2 semantics (v2.9.2): all confidence columns (confidence,
//  legacyConfidence, newConfidence, confThreshold) are normalized to the
//  0-1 scale. In v1, legacyConfidence was stored on the 0-100 scale;
//  v2 rows are the only rows the collector produces. Column layout is
//  identical to v1 (append-only preserved).
//
//  v3 semantics (Sprint 17 Evidence Capture): the runtime scores with
//  the rule-layer architecture (rule + layer + evidence flags), which
//  the v1/v2 columns never captured (16.1B: all component raws zero in
//  v3.0 rows). v3 appends 23 observation columns: schema metadata,
//  rule-level evidence (fired rule id/name, pre-weight score and
//  confidence, evidence ids), layer decomposition (structural/
//  liquidity/confirmation/total raws), tristate evidence flags and the
//  signal creation time.  All v2 columns keep their exact positions and
//  semantics; v3 is strictly append-only over v2.  Structural
//  diagnostics refuse schemaVersion < 3 (see CalibrationStructural).
//
//  v3.1 semantics (Sprint 20 TC01, schemaVersion = 4): appends 7 more
//  columns at the END: layerOrderBlock / layerFVG (structural split by
//  component, telemetry-only — zero behavior change), FVG classifier
//  serialization (fvgClass/fvgSize/fvgStrength — populated by TC04) and
//  gap lifecycle timestamps (fvgCreatedTime/fvgFillTime — populated by
//  TC04).  v3 files (68 columns) remain readable unchanged; v3.1 is
//  strictly append-only over v3.
//
//  v5 semantics (Sprint 22 RL-HYP-01, schemaVersion = 5): appends 3
//  more columns at the END: swingQualifyingId / swingAmplitude (the
//  k*ATR(14) significance threshold at decision time) / gateDecision
//  (ADMIT | GATE-OUT | OFF) — the swing-significance admission gate
//  telemetry required by the frozen Sprint 22 protocol (§14; proves the
//  gate operated, §11.3b).  Defaults are neutral (0 / 0.0 / "OFF") so
//  non-gated rows stay byte-identical to ungated v3.1 rows in all
//  shared columns.  v3.1 files (75 columns) remain readable unchanged;
//  v5 is strictly append-only over v3.1.
//
//  v6 semantics (Sprint 25B B25-01, schemaVersion = 6): appends 3
//  provenance columns at the END: runId (unique per EA process run,
//  self-generated by the collector at Init) / buildTag (compile parse
//  time of the EA binary, `__DATETIME__`) / gitHead (repo commit the
//  TT01 harness rewrites into Telemetry/TelemetryGitHead.mqh before
//  compiling the tranche binaries and restores the default after; the
//  collector reads the compile-time constant TELEMETRY_GIT_HEAD
//  ("unknown" for manual/ED01 builds).  Compile-time (not a runtime
//  file read) because the tester stages FILE_COMMON in an ephemeral
//  agent sandbox that cannot see pre-seeded harness files).  These are
//  row-stamped, constant per run, and carry NO behavioral meaning — the
//  configFingerprint is intentionally NOT extended (identity is not
//  part of the decision configuration).  v5 files (78 columns) remain
//  readable unchanged; v6 is strictly append-only over v5.
//+------------------------------------------------------------------+
#ifndef __TELEMETRY_TYPES_MQH__
#define __TELEMETRY_TYPES_MQH__

#include "../Utils/Constants.mqh"
#include "../Confluence/ConfluenceTypes.mqh"
#include "../Entry/EntryTypes.mqh"

//--- Canonical EA version used by the configuration fingerprint.
#define TELEMETRY_EA_VERSION "v3.0"

#define TELEMETRY_SCHEMA_VERSION     6
#define MAX_TELEMETRY_VALIDATORS     12
#define TELEMETRY_COMPONENT_COUNT    6

//--- Schema v3 identity (Sprint 17 Evidence Capture). The schema
//    fingerprint TelemetrySchemaId = "v3.0" combines schemaVersion and
//    evidenceContract; downstream tooling refuses on mismatch without
//    relying on file naming.
#define TELEMETRY_SCORE_ARCHITECTURE   "rule-layer-v1"   // versioned scoring architecture (rule-layer-v2 will exist someday)
#define TELEMETRY_TELEMETRY_ARCHITECTURE "rule-layer"    // decomposition model of componentData
#define TELEMETRY_EVIDENCE_CONTRACT    "2026-08"         // contract revision; bump on any semantic change
#define TELEMETRY_CONFIDENCE_MODEL     "raw"             // transform state of the score

//--- Tristate evidence semantics (refinement B): a flag the runtime did
//    not evaluate must not be recorded as FALSE.
enum ENUM_EVIDENCE_STATE
{
    EV_UNKNOWN = 0,
    EV_FALSE,
    EV_TRUE
};

//--- CSV column order — part of the frozen v1 contract. Append-only.
#define TELEMETRY_CSV_HEADER_V1 \
    "schemaVersion,configFingerprint,timestamp,symbol,timeframe,eaVersion," \
    "decisionId,direction,confidence," \
    "structureRaw,structureWeight,structureContribution," \
    "obRaw,obWeight,obContribution," \
    "fvgRaw,fvgWeight,fvgContribution," \
    "trendRaw,trendWeight,trendContribution," \
    "liquidityRaw,liquidityWeight,liquidityContribution," \
    "pdRaw,pdWeight,pdContribution," \
    "validatorResults,confThreshold,newDecision,legacyDecision," \
    "decisionMatch,directionMatch,legacyConfidence,newConfidence,disabledValidators," \
    "outcomeSource,outcome,rMultiple,barsHeld,exitReason,entryPrice,exitPrice," \
    "actualOutcome,actualOutcomeSource"

//--- Active v2 header (v2.9.2): identical 45 columns; all confidence
//    columns (confidence, confThreshold, legacyConfidence, newConfidence)
//    are normalized to 0-1.
#define TELEMETRY_CSV_HEADER_V2 \
    "schemaVersion,configFingerprint,timestamp,symbol,timeframe,eaVersion," \
    "decisionId,direction,confidence," \
    "structureRaw,structureWeight,structureContribution," \
    "obRaw,obWeight,obContribution," \
    "fvgRaw,fvgWeight,fvgContribution," \
    "trendRaw,trendWeight,trendContribution," \
    "liquidityRaw,liquidityWeight,liquidityContribution," \
    "pdRaw,pdWeight,pdContribution," \
    "validatorResults,confThreshold,newDecision,legacyDecision," \
    "decisionMatch,directionMatch,legacyConfidence,newConfidence,disabledValidators," \
    "outcomeSource,outcome,rMultiple,barsHeld,exitReason,entryPrice,exitPrice," \
    "actualOutcome,actualOutcomeSource"

//--- Active v3 header (Sprint 17): 68 columns = v2 (45) + 23 evidence
//    columns appended at the END. Frozen once collection starts.
#define TELEMETRY_CSV_HEADER_V3 \
    TELEMETRY_CSV_HEADER_V2 "," \
    "scoreArchitecture,telemetryArchitecture,evidenceContract,confidenceModel,componentData," \
    "firedRuleId,ruleName,ruleScore,ruleConfidence,ruleEvidenceCount,ruleEvidenceIds,trendAligned," \
    "layerStructural,layerLiquidity,layerConfirmation,layerTotal," \
    "hasBOS,hasCHOCH,hasOrderBlock,hasFVG,hasProtectedPoint,hasLiquiditySweep," \
    "signalTime"

//--- Active v3.1 header (Sprint 20 TC01): 75 columns = v3 (68) + 7
//    observation columns appended at the END. Strictly append-only.
//    fvgClass/fvgSize/fvgStrength and gap timestamps are populated by
//    TC04; until then rows carry UNKNOWN / 0.
#define TELEMETRY_CSV_HEADER_V31 \
    TELEMETRY_CSV_HEADER_V3 "," \
    "layerOrderBlock,layerFVG," \
    "fvgClass,fvgSize,fvgStrength," \
    "fvgCreatedTime,fvgFillTime"

//--- Active v5 header (Sprint 22 RL-HYP-01): 78 columns = v3.1 (75) + 3
//    swing-gate columns appended at the END. Strictly append-only over
//    v3.1.  The gate columns carry neutral defaults (0 / 0.0 / "OFF")
//    until the gate runs.
#define TELEMETRY_CSV_HEADER_V5 \
    TELEMETRY_CSV_HEADER_V31 "," \
    "swingQualifyingId,swingAmplitude,gateDecision"

//--- Active v6 header (Sprint 25B B25-01): 81 columns = v5 (78) + 3
//    provenance columns appended at the END. Strictly append-only over
//    v5.  Identity values are stamped by the collector at Record time
//    and are constant per run (see TelemetryCollector).  Files are
//    named telemetry_v6_YYYYMMDD.csv.
#define TELEMETRY_CSV_HEADER_V6 \
    TELEMETRY_CSV_HEADER_V5 "," \
    "runId,buildTag,gitHead"

enum ENUM_TELEMETRY_OUTCOME
{
    TELEMETRY_OUTCOME_UNKNOWN = 0,
    TELEMETRY_OUTCOME_WIN,
    TELEMETRY_OUTCOME_LOSS,
    TELEMETRY_OUTCOME_BREAKEVEN
};

enum ENUM_OUTCOME_SOURCE
{
    OUTCOME_SOURCE_NONE = 0,
    OUTCOME_SOURCE_SIMULATED,
    OUTCOME_SOURCE_ACTUAL
};

enum ENUM_EXIT_REASON
{
    EXIT_REASON_NONE = 0,
    EXIT_REASON_TP,
    EXIT_REASON_SL,
    EXIT_REASON_BREAKEVEN,
    EXIT_REASON_HORIZON
};

enum ENUM_CALIB_EXIT_POLICY
{
    CALIB_POLICY_FIXED_RR = 0,
    CALIB_POLICY_ENTRY_RESOLVER,
    CALIB_POLICY_ATR,
    CALIB_POLICY_TRAILING
};

//--- Per-validator result recorded inside a telemetry row.
struct TelemetryValidatorResult
{
    string name;
    int    result;   // ENUM_FILTER_RESULT: 0=PASS, 1=WARNING, 2=FAIL

    TelemetryValidatorResult(void)
        : name("")
        , result(FILTER_PASS)
    {}
};

//--- Simulated forward outcome produced by the outcome simulator.
struct SimulatedOutcome
{
    ENUM_TELEMETRY_OUTCOME outcome;
    double              rMultiple;
    int                 barsHeld;
    ENUM_EXIT_REASON    exitReason;
    double              entryPrice;
    double              exitPrice;

    SimulatedOutcome(void)
        : outcome(TELEMETRY_OUTCOME_UNKNOWN)
        , rMultiple(0.0)
        , barsHeld(0)
        , exitReason(EXIT_REASON_NONE)
        , entryPrice(0.0)
        , exitPrice(0.0)
    {}
};

// @frozen v2.9
// @frozen v2.9.2 (schemaVersion = 2: confidence columns normalized 0-1)
//--- One decision = one telemetry row.  Frozen contract (see header).
//    Schema freeze: rows must stay CSV-compatible with telemetry_v2_*.
//    Any schema change requires a new schemaVersion + reader migration.
struct TelemetryRow
{
    uint     schemaVersion;
    ulong   configFingerprint;
    datetime timestamp;
    string   symbol;
    int      timeframe;          // ENUM_TIMEFRAMES
    string   eaVersion;
    int      decisionId;         // run-local monotonic id
    int      direction;          // ConfluenceDirection
    double   confidence;         // 0-1 (new-engine decision confidence, v2)

    //--- Component raw scores, weights and contributions (all three stored).
    double structureRaw, structureWeight, structureContribution;
    double obRaw,        obWeight,        obContribution;
    double fvgRaw,       fvgWeight,       fvgContribution;
    double trendRaw,     trendWeight,     trendContribution;
    double liquidityRaw, liquidityWeight, liquidityContribution;
    double pdRaw,        pdWeight,        pdContribution;

    //--- Per-validator outcomes (packed as "Name=0|Name=2|..." in CSV).
    TelemetryValidatorResult validators[MAX_TELEMETRY_VALIDATORS];
    int      validatorCount;

    //--- Confidence threshold that was active for this row (enables exact replay). 0-1.
    double   confThreshold;

    //--- Decisions.
    bool     newDecision;
    bool     legacyDecision;
    bool     decisionMatch;    // new vs legacy qualification agreement
    bool     directionMatch;   // legacy decision direction vs new decision direction
    double   legacyConfidence; // 0-1 (v2; was 0-100 in v1)
    double   newConfidence;    // 0-1
    string   disabledValidators;   // comma-separated, sorted

    //--- Simulated outcome (settled for every row with a direction).
    int      outcomeSource;        // ENUM_OUTCOME_SOURCE
    int      outcome;              // ENUM_TELEMETRY_OUTCOME
    double   rMultiple;
    int      barsHeld;
    int      exitReason;           // ENUM_EXIT_REASON
    double   entryPrice;
    double   exitPrice;

    //--- RESERVED (must remain empty until used; never repurpose).
    int      actualOutcome;        // reserved
    int      actualOutcomeSource;  // reserved

    //--- Schema v3 evidence columns (Sprint 17; append-only over v2).
    //    Metadata (schema identity; refusal checks key off these).
    string   scoreArchitecture;
    string   telemetryArchitecture;
    string   evidenceContract;
    string   confidenceModel;
    int      componentData;        // 1 = row carries rule/layer/evidence observations

    //--- Rule-level evidence (pre-weighting observations).
    int      firedRuleId;          // RuleType enum value (frozen)
    string   ruleName;             // human-readable name (may evolve)
    int      ruleScore;            // 0-100, before any weighting
    double   ruleConfidence;       // 0-1, before weighting
    int      ruleEvidenceCount;
    string   ruleEvidenceIds;      // packed "id1,id2,..."
    int      trendAligned;         // ENUM_EVIDENCE_STATE

    //--- Layer decomposition (the v3.0 components, pre-normalization).
    //    Prefix "layer" keeps these distinct from the legacy 6-component
    //    columns (structureRaw/liquidityRaw/...).
    int      layerStructural;      // 0-50
    int      layerLiquidity;       // 0-30
    int      layerConfirmation;    // 0-20
    int      layerTotal;           // 0-100 (= 100 * confidence)

    //--- Evidence flags (tristate: ENUM_EVIDENCE_STATE).
    int      hasBOS;
    int      hasCHOCH;
    int      hasOrderBlock;
    int      hasFVG;
    int      hasProtectedPoint;
    int      hasLiquiditySweep;

    datetime signalTime;           // signal creation time (decision capture time stays in `timestamp`)

    //--- Schema v3.1 evidence columns (Sprint 20 TC01; append-only over
    //    v3).  Structural split by component (telemetry-only).
    int      layerOrderBlock;      // OB contribution to structural (0-30)
    int      layerFVG;             // FVG contribution to structural (0-30)

    //--- FVG classifier serialization (populated by TC04; UNKNOWN/0 before).
    string   fvgClass;             // REVERSAL | BREAKAWAY | CONTINUATION | UNKNOWN
    string   fvgSize;              // SMALL | MEDIUM | LARGE | UNKNOWN
    string   fvgStrength;          // WEAK | NORMAL | STRONG | UNKNOWN
    datetime fvgCreatedTime;       // gap creation time (0 until TC04 wires timestamps)
    datetime fvgFillTime;          // gap fill time (0 = not filled)

    //--- Schema v5 swing-gate columns (Sprint 22 RL-HYP-01; append-only
    //    over v3.1). Populated by SwingSignificanceGate (§5/§14); the
    //    gate-OFF defaults (0 / 0.0 / "OFF") keep every shared column
    //    byte-identical to the ungated B8 row (gate 3b).
    int      swingQualifyingId;    // qualifying structural pivot id (0 = none)
    double   swingAmplitude;       // k*ATR(14) significance threshold at decision time
    string   gateDecision;         // ADMIT | GATE-OUT | OFF

    //--- Schema v6 provenance columns (Sprint 25B B25-01; append-only
    //    over v5).  Stamped by the collector at Record time; constant
    //    per run; carry NO behavioral meaning (not part of the
    //    configFingerprint).  Empty strings in rows built directly by
    //    unit tests are fine — the collector fills them.
    string   runId;                // unique per EA process run (self-generated)
    string   buildTag;             // EA binary compile parse time (`__DATETIME__`)
    string   gitHead;              // compile-time constant (TelemetryGitHead.mqh); "unknown" for manual builds

    TelemetryRow(void)
        : schemaVersion(TELEMETRY_SCHEMA_VERSION)
        , configFingerprint(0)
        , timestamp(0)
        , symbol("")
        , timeframe((int)PERIOD_CURRENT)
        , eaVersion(TELEMETRY_EA_VERSION)
        , decisionId(0)
        , direction((int)CONFLUENCE_NONE)
        , confidence(0.0)
        , structureRaw(0.0), structureWeight(0.0), structureContribution(0.0)
        , obRaw(0.0),        obWeight(0.0),        obContribution(0.0)
        , fvgRaw(0.0),       fvgWeight(0.0),       fvgContribution(0.0)
        , trendRaw(0.0),     trendWeight(0.0),     trendContribution(0.0)
        , liquidityRaw(0.0), liquidityWeight(0.0), liquidityContribution(0.0)
        , pdRaw(0.0),        pdWeight(0.0),        pdContribution(0.0)
        , validatorCount(0)
        , confThreshold(0.60)
        , newDecision(false)
        , legacyDecision(false)
        , decisionMatch(false)
        , directionMatch(false)
        , legacyConfidence(0.0)
        , newConfidence(0.0)
        , disabledValidators("")
        , outcomeSource((int)OUTCOME_SOURCE_NONE)
        , outcome((int)TELEMETRY_OUTCOME_UNKNOWN)
        , rMultiple(0.0)
        , barsHeld(0)
        , exitReason((int)EXIT_REASON_NONE)
        , entryPrice(0.0)
        , exitPrice(0.0)
        , actualOutcome((int)TELEMETRY_OUTCOME_UNKNOWN)
        , actualOutcomeSource((int)OUTCOME_SOURCE_NONE)
        , scoreArchitecture(TELEMETRY_SCORE_ARCHITECTURE)
        , telemetryArchitecture(TELEMETRY_TELEMETRY_ARCHITECTURE)
        , evidenceContract(TELEMETRY_EVIDENCE_CONTRACT)
        , confidenceModel(TELEMETRY_CONFIDENCE_MODEL)
        , componentData(0)
        , firedRuleId(0)
        , ruleName("")
        , ruleScore(0)
        , ruleConfidence(0.0)
        , ruleEvidenceCount(0)
        , ruleEvidenceIds("")
        , trendAligned((int)EV_UNKNOWN)
        , layerStructural(0)
        , layerLiquidity(0)
        , layerConfirmation(0)
        , layerTotal(0)
        , hasBOS((int)EV_UNKNOWN)
        , hasCHOCH((int)EV_UNKNOWN)
        , hasOrderBlock((int)EV_UNKNOWN)
        , hasFVG((int)EV_UNKNOWN)
        , hasProtectedPoint((int)EV_UNKNOWN)
        , hasLiquiditySweep((int)EV_UNKNOWN)
        , signalTime(0)
        , layerOrderBlock(0)
        , layerFVG(0)
        , fvgClass("UNKNOWN")
        , fvgSize("UNKNOWN")
        , fvgStrength("UNKNOWN")
        , fvgCreatedTime(0)
        , fvgFillTime(0)
        , swingQualifyingId(0)
        , swingAmplitude(0.0)
        , gateDecision("OFF")
        , runId("")
        , buildTag("")
        , gitHead("")
    {}

    void SetComponent(ENUM_CONFLUENCE_COMPONENT type, double raw, double weight, double contribution)
    {
        switch(type)
        {
            case COMPONENT_STRUCTURE:        structureRaw = raw;        structureWeight = weight;        structureContribution = contribution; break;
            case COMPONENT_ORDER_BLOCK:      obRaw = raw;               obWeight = weight;               obContribution = contribution;          break;
            case COMPONENT_FVG:              fvgRaw = raw;              fvgWeight = weight;              fvgContribution = contribution;         break;
            case COMPONENT_TREND:            trendRaw = raw;            trendWeight = weight;            trendContribution = contribution;       break;
            case COMPONENT_LIQUIDITY:        liquidityRaw = raw;        liquidityWeight = weight;        liquidityContribution = contribution;   break;
            case COMPONENT_PREMIUM_DISCOUNT: pdRaw = raw;               pdWeight = weight;               pdContribution = contribution;          break;
        }
    }

    double GetRaw(ENUM_CONFLUENCE_COMPONENT type) const
    {
        switch(type)
        {
            case COMPONENT_STRUCTURE:        return structureRaw;
            case COMPONENT_ORDER_BLOCK:      return obRaw;
            case COMPONENT_FVG:              return fvgRaw;
            case COMPONENT_TREND:            return trendRaw;
            case COMPONENT_LIQUIDITY:        return liquidityRaw;
            case COMPONENT_PREMIUM_DISCOUNT: return pdRaw;
        }
        return 0.0;
    }

    //--- Recompute weighted confidence from stored raw scores (offline replay).
    double ReplayConfidence(const double &weights[]) const
    {
        double total = 0.0;
        total += structureRaw * weights[0] / 100.0;
        total += obRaw        * weights[1] / 100.0;
        total += fvgRaw       * weights[2] / 100.0;
        total += liquidityRaw * weights[3] / 100.0;
        total += trendRaw     * weights[4] / 100.0;
        total += pdRaw        * weights[5] / 100.0;
        if(total < 0.0) total = 0.0;
        if(total > 100.0) total = 100.0;
        return total;
    }

    //--- Pack validator results into a stable "Name=0|Name=2" string.
    string PackValidatorResults(void) const
    {
        string out = "";
        for(int i = 0; i < validatorCount; i++)
        {
            if(out != "") out += "|";
            out += validators[i].name + "=" + IntegerToString(validators[i].result);
        }
        return out;
    }

    bool UnpackValidatorResults(const string packed)
    {
        validatorCount = 0;
        string parts[];
        int n = StringSplit(packed, '|', parts);
        for(int i = 0; i < n && validatorCount < MAX_TELEMETRY_VALIDATORS; i++)
        {
            int eq = StringFind(parts[i], "=");
            if(eq <= 0)
                continue;
            validators[validatorCount].name = StringSubstr(parts[i], 0, eq);
            validators[validatorCount].result = (int)StringToInteger(StringSubstr(parts[i], eq + 1));
            validatorCount++;
        }
        return true;
    }

    bool HasValidatorResult(const string name) const
    {
        for(int i = 0; i < validatorCount; i++)
        {
            if(validators[i].name == name)
                return true;
        }
        return false;
    }

    int GetValidatorResult(const string name) const
    {
        for(int i = 0; i < validatorCount; i++)
        {
            if(validators[i].name == name)
                return validators[i].result;
        }
        return -1;
    }

    //--- Replay the full new-engine decision for a given confidence threshold.
    //    The confluence gate is re-evaluated; all other validators use stored
    //    results (a missing result is treated as PASS â€” with collectAll
    //    telemetry every enabled validator is recorded, so missing means
    //    the validator was disabled for this configuration).
    bool ReplayDecision(double threshold) const
    {
        if(confidence < threshold)
            return false;
        for(int i = 0; i < validatorCount; i++)
        {
            if(validators[i].name == "ConfluenceValidator")
                continue;
            if(validators[i].result == FILTER_FAIL)
                return false;
        }
        return true;
    }
};

//--- Frozen rule-ID -> name mapping (refinement C: ids are stable,
//    names may evolve). Mirrors the RuleType enum order.
string TelemetryRuleName(const int ruleId)
{
    switch(ruleId)
    {
        case 1:  return "BOS_OB_BULLISH";
        case 2:  return "BOS_OB_BEARISH";
        case 3:  return "OB_FVG_BULLISH";
        case 4:  return "OB_FVG_BEARISH";
        case 5:  return "LIQUIDITY_BOS_BULLISH";
        case 6:  return "LIQUIDITY_BOS_BEARISH";
        case 7:  return "CHOCH_OB_REVERSAL";
    }
    return "";
}

//--- Map a runtime boolean observation to the tristate contract.
int TelemetryEvidenceState(const bool evaluated)
{
    return evaluated ? (int)EV_TRUE : (int)EV_FALSE;
}

//--- Runtime calibration configuration (EA inputs -> engines).
struct CalibrationConfig
{
    bool     telemetryEnabled;
    double   minConfidence;
    double   weights[TELEMETRY_COMPONENT_COUNT]; // S, OB, FVG, Liq, Trend, PD
    string   disabledValidators;                  // comma-separated (unsorted input)
    int      exitPolicy;                          // ENUM_CALIB_EXIT_POLICY
    double   slR;
    double   tpR;
    int      maxHoldBars;
    bool     useProductionProviders;
    string   eaVersion;
    string   spreadMode;                          // "quote" | "tick" | "fixed"
    int      brokerDigits;

    //--- GR01: per-family admission floors (mirror ConfluenceConfig so
    //    the fingerprint records the routing policy that affects
    //    decision outcomes).  Evidence-calibrated values from the frozen
    //    Sprint 17 funnel (docs/Sprint20_GR01_Decision.md).
    double   familyFloorLiquidity;
    double   familyFloorFVG;
    double   familyFloorOrderBlock;
    double   familyFloorBOS;
    double   familyFloorCHOCH;
    double   familyFloorUnknown;

    CalibrationConfig(void)
        : telemetryEnabled(true)
        , minConfidence(0.60)
        , exitPolicy((int)CALIB_POLICY_FIXED_RR)
        , slR(1.0)
        , tpR(2.0)
        , maxHoldBars(50)
        , useProductionProviders(false)
        , eaVersion(TELEMETRY_EA_VERSION)
        , spreadMode("quote")
        , brokerDigits(5)
        , familyFloorLiquidity(0.60)
        , familyFloorFVG(0.35)
        , familyFloorOrderBlock(0.35)
        , familyFloorBOS(0.35)
        , familyFloorCHOCH(0.35)
        , familyFloorUnknown(0.35)
    {
        weights[0] = 25.0;
        weights[1] = 20.0;
        weights[2] = 15.0;
        weights[3] = 15.0;
        weights[4] = 15.0;
        weights[5] = 10.0;
    }
};

#endif

