# 25B_SuiteCheck.ps1 - Sprint 25B (B25-01/B25-02) suite-green check
#   powershell -File Tools\25B\25B_SuiteCheck.ps1
# Compiles the 6 canonical harness targets EXACTLY like the TT01 compile phase,
# then runs the headless unit suite and asserts:
#   S1  suite GREEN (GRAND TOTAL, 0 failed)
#   S2  B25-01 identity tests ran: TestCollector_IdentityStamp present, no FAIL
#   S3  B25-02 checkpoint tests ran: TestCollector_CheckpointFlush present, no FAIL
#   S4  the v6 telemetry CSV written during the suite carries the identity
#       columns (81-col header, schemaVersion 6, non-empty runId/buildTag on
#       EVERY row)
#   S5  TELEMETRY_CHECKPOINT_ROWS == 64 in TelemetryCollector.mqh
# This script does NOT touch Tools\TT01 (no gates.jsonl, no run dir) and never
# modifies frozen baselines. Evidence under Tools\25B\artifacts\<runId>.
# Exit 0 = all checks PASS, 1 = any check FAIL.
$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$Root      = (git -C $ScriptDir rev-parse --show-toplevel) -replace "`n", ""
$SC        = if (Test-Path (Join-Path $Root "Experts\SuperCents_X")) { Join-Path $Root "Experts\SuperCents_X" } else { $Root }
$Terminal   = "C:\Program Files\MetaTrader 5\terminal64.exe"
$MetaEditor = "C:\Program Files\MetaTrader 5\metaeditor64.exe"
$TesterRoot = Join-Path $env:APPDATA "MetaQuotes\Tester"
$AgentDir   = Join-Path ((Get-ChildItem -LiteralPath $TesterRoot -Recurse -Directory -Filter "Agent-127.0.0.1-3000" -ErrorAction SilentlyContinue | Select-Object -First 1).FullName) "logs"
$AgentLog   = Join-Path $AgentDir ((Get-Date -Format "yyyyMMdd") + ".log")
$TelemetryDir = Join-Path $env:APPDATA "MetaQuotes\Terminal\Common\Files\Telemetry"
$ArtDir     = Join-Path $SC "Tools\25B\artifacts"

$runId = "25B_SuiteCheck_" + (Get-Date -Format "yyyyMMdd_HHmmss")
$runArt = Join-Path $ArtDir $runId
New-Item -ItemType Directory -Path $runArt -Force | Out-Null

$CompileTargets = @(
    @{ Label = "SuperCents_X";     Path = Join-Path $SC "SuperCents_X.mq5" },
    @{ Label = "CalibrationRunner";Path = Join-Path $SC "CalibrationRunner.mq5" },
    @{ Label = "TestRunner";       Path = Join-Path $SC "Tests\TestRunner.mq5" },
    @{ Label = "TestRunnerEA";     Path = Join-Path $SC "Tests\TestRunnerEA.mq5" },
    @{ Label = "BenchmarkRunner";  Path = Join-Path $SC "benchmarks\BenchmarkRunner.mq5" },
    @{ Label = "BenchmarkRunnerEA";Path = Join-Path $SC "benchmarks\BenchmarkRunnerEA.mq5" }
)

$SuiteIni = @'
[Tester]
Expert=SuperCents_X\Tests\TestRunnerEA.ex5
Symbol=EURUSD
Period=H1
Optimization=0
Model=4
FromDate=2026.01.01
ToDate=2026.01.02
ForwardMode=0
Deposit=10000
Currency=GBP
ProfitInPips=0
Leverage=200
ExecutionMode=1000
OptimizationCriterion=0
Visual=0
ReplaceReport=1
ShutdownTerminal=1
'@

$fail = 0
function Check($label, [bool]$ok, [string]$detail) {
    Write-Host ("  [{0}] {1} - {2}" -f $(if ($ok) { "PASS" } else { "FAIL" }), $label, $detail) -ForegroundColor $(if ($ok) { "Green" } else { "Red" })
    if (-not $ok) { $script:fail++ }
}

#--- S5: checkpoint constant (source-level policy assertion)
$collectorSrc = Get-Content -LiteralPath (Join-Path $SC "Telemetry\TelemetryCollector.mqh") -Raw
$cpMatch = [regex]::Match($collectorSrc, "#define\s+TELEMETRY_CHECKPOINT_ROWS\s+(\d+)")
$cpRows = if ($cpMatch.Success) { [int]$cpMatch.Groups[1].Value } else { -1 }
Check "S5 checkpoint constant" ($cpRows -eq 64) "TELEMETRY_CHECKPOINT_ROWS=$cpRows (expected 64)"

#--- COMPILE phase (mirror of Invoke-TT01Compile)
Write-Host "=== compile ($($CompileTargets.Count) targets) ==="
#--- B25-01: stamp the compile-time gitHead include (mirror of the TT01
#    run-start publish; restored after the suite so the repo stays clean).
$gitHeadFull = git -C $ScriptDir rev-parse HEAD
$gitHeadInc = Join-Path $SC "Telemetry\TelemetryGitHead.mqh"
Set-Content -LiteralPath $gitHeadInc -Value (
    "// generated by 25B_SuiteCheck (B25-01): repo commit for the tranche binaries`r`n" +
    "#define TELEMETRY_GIT_HEAD `"$gitHeadFull`"`r`n") -Encoding ASCII
foreach ($t in $CompileTargets) {
    $log = Join-Path $runArt ("compile_" + $t.Label + ".log")
    $ex5Path = $t.Path -replace "\.mq5$", ".ex5"
    $pre = if (Test-Path -LiteralPath $ex5Path) { (Get-Item -LiteralPath $ex5Path).LastWriteTime } else { [datetime]::MinValue }
    $t0 = Get-Date
    Start-Process -FilePath $MetaEditor -ArgumentList "/compile:`"$($t.Path)`" /log:`"$log`"" -Wait | Out-Null
    Start-Sleep -Seconds 2
    $post = if (Test-Path -LiteralPath $ex5Path) { (Get-Item -LiteralPath $ex5Path).LastWriteTime } else { [datetime]::MinValue }
    $line = (Get-Content -LiteralPath $log -ErrorAction SilentlyContinue | Select-String "Result:" | Select-Object -Last 1).Line
    $refreshed = ($post -ge $t0.AddSeconds(-5))
    $errs = if ($line -match "(\d+) errors") { [int]$Matches[1] } else { -1 }
    Check ("C-" + $t.Label) ($errs -eq 0 -and $refreshed) ("result: $($line -replace '.*Result: ', '') refreshed=$refreshed")
}
$c = @(Get-Content -LiteralPath $gitHeadInc)
for ($i = 0; $i -lt $c.Count; $i++) {
    if ($c[$i] -match '^\s*#define\s+TELEMETRY_GIT_HEAD') { $c[$i] = '#define TELEMETRY_GIT_HEAD "unknown"' }
}
Set-Content -LiteralPath $gitHeadInc -Value $c -Encoding ASCII

#--- SUITE phase
Write-Host "=== suite (headless) ==="
$ini = Join-Path $runArt "suite.ini"
Set-Content -LiteralPath $ini -Value $SuiteIni -Encoding ASCII
$p = Get-Process terminal64 -ErrorAction SilentlyContinue
if ($p) { Stop-Process -Id $p.Id -Force -ErrorAction SilentlyContinue; Start-Sleep -Seconds 5 }
Start-Process -FilePath $Terminal -ArgumentList "/config:`"$ini`"" -WorkingDirectory $Root | Out-Null
$deadline = (Get-Date).AddSeconds(720)
do { Start-Sleep -Seconds 3; $p = Get-Process terminal64 -ErrorAction SilentlyContinue } while ($p -and (Get-Date) -lt $deadline)
if ($p) { Check "suite exit" $false "terminal did not exit within timeout" }
else {
    $all = @(Get-Content -LiteralPath $AgentLog -Tail 4000 -ErrorAction SilentlyContinue)
    $gtLines = @(for ($i = 0; $i -lt $all.Count; $i++) { if ($all[$i] -match "GRAND TOTAL") { $i } })
    if ($gtLines.Count -eq 0) {
        Check "S1 suite GREEN" $false "no GRAND TOTAL block found in $AgentLog"
    } else {
        $start = if ($gtLines.Count -gt 1) { $gtLines[-2] + 1 } else { 0 }
        $slice = @($all[$start..$gtLines[-1]])
        $slice | Set-Content -LiteralPath (Join-Path $runArt "suite_journal_slice.log") -Encoding UTF8
        $grand = $slice | Where-Object { $_ -match "GRAND TOTAL" } | Select-Object -Last 1
        $failed = if ($grand -match "GRAND TOTAL: (\d+)/(\d+) passed, (\d+) failed") { [int]$Matches[3] } else { -1 }
        Check "S1 suite GREEN" ($failed -eq 0) ($(if ($failed -eq -1) { "GRAND TOTAL unparseable" } else { $grand -replace "^.*GRAND TOTAL", "GRAND TOTAL" }))

        $streamed = @(Select-String -LiteralPath $AgentLog -Pattern '>>> BUILD 25A-RUNTIME-01|>>> BUILD 25B-PROD-01|FAIL \[' -ErrorAction SilentlyContinue | Select-Object -Last 1000)
        $buildLine = [string](@($streamed | Where-Object { $_.Line -match ">>> BUILD " } | Select-Object -Last 1 | ForEach-Object { $_.Line }) | Select-Object -First 1)
        $fails = @($streamed | Where-Object { $_.Line -match "FAIL \[" } | ForEach-Object { [string]$_.Line })
        if (-not $buildLine) { $buildLine = "<none>" }
        Set-Content -LiteralPath (Join-Path $runArt "runtime_identity.log") -Value @(
            ("buildLine  = " + $buildLine)
            ("failLines  = " + $fails.Count)
            $fails
        ) -Encoding UTF8

        $identFail = @($fails | Where-Object { $_ -match "TestCollector_IdentityStamp|TestCollector_CheckpointFlush|TestHealth_V6IdentityRoundTrip|TestHeader_V6ColumnCount|TestParse_V6IdentityRoundTrip" })
        $tagOk = ($buildLine -match '>>> BUILD (25A-RUNTIME-01|25B-PROD-01) tag="\d{4}\.\d{2}\.\d{2} \d{2}:\d{2}:\d{2}"')
        Check "S2 identity tests present+green" (($identFail.Count -eq 0) -and $tagOk) "no FAIL for the B25 identity/checkpoint tests; buildLine tag valid: $tagOk"
        Check "S3 checkpoint tests present+green" ($identFail.Count -eq 0) "TestCollector_CheckpointFlush FAIL lines: $($identFail.Count)"
    }
}

#--- S4: v6 telemetry CSV written during the suite carries identity everywhere
$csvs = @(Get-ChildItem -LiteralPath $TelemetryDir -File -Filter "telemetry_v6_*.csv" -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending | Select-Object -First 3)
$checkCsv = $null
foreach ($c in $csvs) {
    if ($c.LastWriteTime -gt (Get-Date).AddMinutes(-30)) { $checkCsv = $c; break }
}
if ($null -eq $checkCsv) {
    Check "S4 v6 csv identity" $false "no recent telemetry_v6_*.csv in $TelemetryDir"
} else {
    $lines = @(Get-Content -LiteralPath $checkCsv.FullName -ErrorAction SilentlyContinue)
    $hdr = $lines[0].Split(",")
    $rows = $lines | Select-Object -Skip 1 | Where-Object { $_.Trim().Length -gt 0 }
    $badRunId = @($rows | Where-Object { ($_ -split ",")[78] -notmatch '^RUN-' }).Count
    $badBuild = @($rows | Where-Object { ($_ -split ",")[79] -notmatch '^\d{4}\.\d{2}\.\d{2} ' }).Count
    $badSchema = @($rows | Where-Object { ($_ -split ",")[0] -ne "6" }).Count
    Check "S4 v6 csv identity" ($hdr.Count -eq 81 -and $hdr[78] -eq "runId" -and $hdr[80] -eq "gitHead" -and $badSchema -eq 0 -and $badRunId -eq 0 -and $badBuild -eq 0) `
        ("$($checkCsv.Name): cols=$($hdr.Count) rows=$($rows.Count) badSchema=$badSchema badRunId=$badRunId badBuild=$badBuild")
    Copy-Item -LiteralPath $checkCsv.FullName -Destination (Join-Path $runArt ("telemetry_" + $checkCsv.Name)) -Force
}

Write-Host ""
if ($fail -eq 0) { Write-Host "25B SUITE CHECK: ALL PASS - evidence $runArt" -ForegroundColor Green; exit 0 }
Write-Host "25B SUITE CHECK: $fail FAILURES - evidence $runArt" -ForegroundColor Red; exit 1

